# H2 Console aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datenbank URL
spring.datasource.url=jdbc:h2:mem:speeddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Einstellungen
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Batch Job nicht mehr automatisch direkt beim Start ausführen (wird vom Scheduler übernommen)
spring.batch.job.enabled=false